import { ArrowLeft, ChevronRight, GitCompareArrows, Scale } from 'lucide-react';
import { useState } from 'react';
import './_group.css';

const offers = [
  { id: 'alfa', name: 'Oferta_ALFA_Budownictwo.pdf', supplier: 'ALFA Budownictwo' },
  { id: 'beta', name: 'Oferta_BETA_Materiały.pdf', supplier: 'BETA Materiały' },
  { id: 'gamma', name: 'Oferta_GAMMA_Trade.pdf', supplier: 'GAMMA Trade' },
];

export function CurrentOffers() {
  const [selected, setSelected] = useState<string[]>([]);
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : current.length < 2 ? [...current, id] : current);
  return <div className="sogo-noise min-h-screen bg-background text-foreground"><main className="mx-auto max-w-[1400px] p-5 md:p-8 lg:p-10">
    <div className="flex flex-col justify-between gap-5 border-b border-border pb-6 md:flex-row md:items-end"><div><a href="#" className="inline-flex items-center gap-2 text-xs font-bold text-muted-foreground"><ArrowLeft size={14} /> Wszystkie porównania</a><p className="mt-4 font-mono text-[10px] uppercase tracking-[0.22em] text-accent">03 / ZAKUP</p><h1 className="mt-2 font-display text-2xl font-bold tracking-[-0.04em]">Nowe porównanie</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Porównaj dokładnie dwie przeanalizowane oferty według zapisanej listy materiałów.</p></div><button disabled={selected.length !== 2} className="inline-flex h-10 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-50"><GitCompareArrows size={16} /> Porównaj oferty</button></div>
    <div className="mt-8 grid min-w-0 gap-5 lg:grid-cols-[minmax(260px,300px)_minmax(0,1fr)]"><aside className="order-2 min-w-0 space-y-3 lg:order-1"><div className="rounded-2xl border border-border bg-card/70 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold">Lista materiałów</p><p className="mt-1 text-xs text-muted-foreground">Materiały budowlane · wersja 3</p></div><span className="rounded-full bg-secondary px-2 py-1 font-mono text-[10px] text-muted-foreground">18 pozycji</span></div><p className="mt-2 text-xs text-muted-foreground">Obszar zakupowy: Ogólne</p><a href="#" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-accent underline underline-offset-2">Edytuj listę materiałów <ChevronRight size={14} /></a></div><label className="flex cursor-pointer items-start gap-3 rounded-2xl border border-primary/25 bg-primary/10 p-4 text-sm leading-6"><input type="checkbox" className="mt-1 accent-primary" /> <span>Porównaj według listy materiałów <strong>Materiały budowlane</strong>, wersja <strong>3</strong>.</span></label><div className="rounded-2xl border border-border bg-card/70 p-4"><div className="flex items-center justify-between"><p className="text-sm font-bold">Oferty do porównania</p><span className="font-mono text-[10px] text-muted-foreground">{selected.length} / 2</span></div><p className="mt-2 text-xs leading-5 text-muted-foreground">Wybierz dwie oferty ze statusem „Do sprawdzenia”. Ich kolejność wyznacza kolumny A i B.</p><div className="mt-4 space-y-2">{offers.map(offer => <button key={offer.id} onClick={() => toggle(offer.id)} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left text-xs ${selected.includes(offer.id) ? 'border-primary bg-primary/10' : 'border-border bg-background'}`}><span className={`grid h-5 w-5 place-items-center rounded border text-[10px] ${selected.includes(offer.id) ? 'border-primary bg-primary text-primary-foreground' : 'border-border'}`}>{selected.includes(offer.id) ? '✓' : ''}</span><span className="min-w-0"><b className="block truncate">{offer.supplier}</b><span className="mt-1 block truncate text-muted-foreground">{offer.name}</span></span></button>)}</div></div></aside><section className="order-1 min-w-0 rounded-2xl border border-border bg-card/70 p-6 sm:p-8 lg:order-2"><div className="grid min-h-[420px] place-items-center text-center"><div><Scale size={32} className="mx-auto text-accent" /><p className="mt-5 font-display text-lg font-bold">Porównanie uruchomisz po potwierdzeniu</p><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-muted-foreground">Wybierz oferty, potwierdź aktualną listę materiałów i kliknij „Porównaj oferty”. Wynik otworzy się na osobnej stronie.</p></div></div></section></div>
  </main></div>;
}