// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/apo-summary/Current.tsx": () => import("../components/mockups/apo-summary/Current.tsx"),
  "./components/mockups/apo-summary/Updated.tsx": () => import("../components/mockups/apo-summary/Updated.tsx"),
  "./components/mockups/apo-workspace-redesign/Current.tsx": () => import("../components/mockups/apo-workspace-redesign/Current.tsx"),
  "./components/mockups/apo-workspace-redesign/Proposed.tsx": () => import("../components/mockups/apo-workspace-redesign/Proposed.tsx"),
  "./components/mockups/sogo-documentation-current/Current.tsx": () => import("../components/mockups/sogo-documentation-current/Current.tsx"),
  "./components/mockups/sogo-documentation-current/ProjectDocumentationUI.tsx": () => import("../components/mockups/sogo-documentation-current/ProjectDocumentationUI.tsx"),
  "./components/mockups/scope-materials/Current.tsx": () => import("../components/mockups/scope-materials/Current.tsx"),
  "./components/mockups/scope-materials/Responsive.tsx": () => import("../components/mockups/scope-materials/Responsive.tsx"),
  "./components/mockups/sogo-public-entry/Current.tsx": () => import("../components/mockups/sogo-public-entry/Current.tsx"),
  "./components/mockups/sogo-public-entry/Proposed.tsx": () => import("../components/mockups/sogo-public-entry/Proposed.tsx"),
  "./components/mockups/sogo-purchase-current/CurrentFiles.tsx": () => import("../components/mockups/sogo-purchase-current/CurrentFiles.tsx"),
  "./components/mockups/sogo-purchase-current/CurrentOffers.tsx": () => import("../components/mockups/sogo-purchase-current/CurrentOffers.tsx")
};
